.travis.yml: run staticcheck and misspell
Fix these two `staticcheck` warnings:

 fsys_windows.go:21:20: error strings should not be capitalized (ST1005)
 internal\frame\util.go:131:4: this value of b is never used (SA4006)

We ignore these two checks because there are failure cases that I'm not
sure is worth fixing:

 $ staticcheck -explain U1000
 Unused code
 $ staticcheck -explain SA4003
 Comparing unsigned values against negative values is pointless